// <auto-generated />
using System;
using IISAdministration.Models.DatabaseModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IISAdministration.Migrations
{
    [DbContext(typeof(ServersContext))]
    [Migration("20190513202632_Metrics")]
    partial class Metrics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IISAdministration.Models.Metrics", b =>
                {
                    b.Property<int>("MetricsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BytesRecvPerSec");

                    b.Property<int>("BytesSentPerSec");

                    b.Property<int>("CpuPercentUsage");

                    b.Property<int>("CurrentConnections");

                    b.Property<int>("Date");

                    b.Property<int>("DayOfWeek");

                    b.Property<int>("IoReadOpsPerSec");

                    b.Property<int>("IoWriteOpsPerSec");

                    b.Property<int>("Processes");

                    b.Property<int>("RequestsPerSecond");

                    b.Property<int>("ServerId");

                    b.Property<int>("SystemCpuPercentUsage");

                    b.Property<long>("SystemMemoryInUse");

                    b.Property<int>("Threads");

                    b.Property<int>("Time");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("MetricsId");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("IISAdministration.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Token");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("ServerId");

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
